# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: exibe.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x65xibe.proto\x12\x05\x65xibe\"\x07\n\x05Vazio\"*\n\x0fMessageResponse\x12\x17\n\x0fmessageResponse\x18\x01 \x01(\t\"3\n\x0fMensagem_Origem\x12\x10\n\x08mensagem\x18\x01 \x01(\t\x12\x0e\n\x06origem\x18\x02 \x01(\t\"\"\n\x0eNumeroResposta\x12\x10\n\x08resposta\x18\x01 \x01(\x05\x32t\n\x05\x45xibe\x12\x39\n\x05\x65xibe\x12\x16.exibe.Mensagem_Origem\x1a\x16.exibe.MessageResponse\"\x00\x12\x30\n\x07termina\x12\x0c.exibe.Vazio\x1a\x15.exibe.NumeroResposta\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'exibe_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_VAZIO']._serialized_start=22
  _globals['_VAZIO']._serialized_end=29
  _globals['_MESSAGERESPONSE']._serialized_start=31
  _globals['_MESSAGERESPONSE']._serialized_end=73
  _globals['_MENSAGEM_ORIGEM']._serialized_start=75
  _globals['_MENSAGEM_ORIGEM']._serialized_end=126
  _globals['_NUMERORESPOSTA']._serialized_start=128
  _globals['_NUMERORESPOSTA']._serialized_end=162
  _globals['_EXIBE']._serialized_start=164
  _globals['_EXIBE']._serialized_end=280
# @@protoc_insertion_point(module_scope)
