# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sala.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nsala.proto\x12\x04sala\"\x07\n\x05Vazio\"*\n\x0fMessageResponse\x12\x17\n\x0fmessageResponse\x18\x01 \x01(\t\"5\n\x10Mensagem_Destino\x12\x10\n\x08mensagem\x18\x01 \x01(\t\x12\x0f\n\x07\x64\x65stino\x18\x02 \x01(\t\"\x1b\n\rIdentificador\x12\n\n\x02id\x18\x01 \x01(\t\"\"\n\x0eNumeroResposta\x12\x10\n\x08resposta\x18\x01 \x01(\x05\"9\n\x0fRegistroDeSaida\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04\x66qdn\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\x05\"*\n\rListaResposta\x12\x19\n\x11lista_de_resposta\x18\x01 \x03(\t2\xd0\x02\n\x04Sala\x12\x38\n\x05\x65nvia\x12\x16.sala.Mensagem_Destino\x1a\x15.sala.MessageResponse\"\x00\x12?\n\x10registra_entrada\x12\x13.sala.Identificador\x1a\x14.sala.NumeroResposta\"\x00\x12?\n\x0eregistra_saida\x12\x15.sala.RegistroDeSaida\x1a\x14.sala.NumeroResposta\"\x00\x12+\n\x05lista\x12\x0b.sala.Vazio\x1a\x13.sala.ListaResposta\"\x00\x12\x38\n\x11\x66inaliza_registro\x12\x0b.sala.Vazio\x1a\x14.sala.NumeroResposta\"\x00\x12%\n\x07termina\x12\x0b.sala.Vazio\x1a\x0b.sala.Vazio\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sala_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_VAZIO']._serialized_start=20
  _globals['_VAZIO']._serialized_end=27
  _globals['_MESSAGERESPONSE']._serialized_start=29
  _globals['_MESSAGERESPONSE']._serialized_end=71
  _globals['_MENSAGEM_DESTINO']._serialized_start=73
  _globals['_MENSAGEM_DESTINO']._serialized_end=126
  _globals['_IDENTIFICADOR']._serialized_start=128
  _globals['_IDENTIFICADOR']._serialized_end=155
  _globals['_NUMERORESPOSTA']._serialized_start=157
  _globals['_NUMERORESPOSTA']._serialized_end=191
  _globals['_REGISTRODESAIDA']._serialized_start=193
  _globals['_REGISTRODESAIDA']._serialized_end=250
  _globals['_LISTARESPOSTA']._serialized_start=252
  _globals['_LISTARESPOSTA']._serialized_end=294
  _globals['_SALA']._serialized_start=297
  _globals['_SALA']._serialized_end=633
# @@protoc_insertion_point(module_scope)
